export enum NODE_ENV {
  DEV = 'development',
  STAGING = 'staging',
  PROD = 'production',
}

export enum ENV {
  NODE_ENV = 'NODE_ENV',
  SWAGGER_USER = 'Raflink',
  SWAGGER_PASSWORD = 'Raflink@2021',
  MONGO_URI = 'MONGO_URI',
  NODE_DEV = 'development',
  COMPANY_EMAIL = 'raflink@co.ng',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  SMTP_HOST = 'SMTP_HOST',
  SMTP_PASS = 'SMTP_PASS',
  SMTP_PORT = 'SMTP_PORT',
  SMTP_USER = 'SMTP_USER',
  SMTP_SECURE = 'SMTP_SECURE',
  EMAIL_FROM = 'EMAIL_FROM',
  ENCRYPTION_KEY = 'ENCRYPTION_KEY',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
}

export enum TEMPLATES {
  WELCOME = 'WELCOME',
  VERIFY = 'VERIFY',
  OTP = 'OTP',
  ONBOARDING = 'ONBOARDING',
  WAITLIST = 'WAITLIST',
}

export enum OTPRELAX {
  RAFLINK_RELAX_OTP = 'XXIGNOREZX',
}

export enum CACHE_METADATA {
  OTP_SERVICE = 'OTP_SERVICE',
}

export enum TEMPLATE_LINK_LAYOUT {
  CLASSIC = 'CLASSIC',
  FEATURED = 'FEATURED',
}

export enum SOCIAL_LINKS_POSITON {
  TOP = 'TOP',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  DOWN = 'DOWN',
}

export enum SOCIALS {
  WEBSITE = 'WEBSITE',
  INSTAGRAM = 'INSTAGRAM',
  TIKTOK = 'TIKTOK',
  YOUTUBE = 'YOUTUBE',
  WHATSAPP = 'WHATSAPP',
}

export enum SubscriptionStatus {
  ACTIVE = 'active',
  CANCELED = 'canceled',
  PAST_DUE = 'past_due',
  TRIALING = 'trialing',
  UNPAID = 'unpaid',
  INCOMPLETE = 'incomplete',
  INCOMPLETE_EXPIRED = 'incomplete_expired',
}

export enum SubscriptionPlan {
  FREE = 'free',
  PRO = 'pro',
}
